# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='featurevalue',
            unique_together=set([('feature', 'value')]),
        ),
    ]
