# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_auto_20170226_1639'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feature',
            table=None,
        ),
    ]
